### ISSUE TITLE
Реализовать корректное сравнение double

### ISSUE THREAD

**Issue by FishKOH** [cpppracticum/cpp-backend-tests-practicum#17]
в тесте test_s02_time_control.py
сравниваются состояния игры посредством сравнения json-строк
при этом возникают проблемы с точностью сравнения чисел с плавающей точкой

пример: 
![image](https://user-images.githubusercontent.com/22637580/205790995-fa3c1b0d-4671-4b13-a347-08385bb80da0.png)

**Comment by wo1f** [comment]
Пофикшено)
